defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-imagenet100-linear-officehome_realworld"
pretrained_feature_extractor: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/trained_models/barlow_twins/c4fzq57y/barlow_twins-imagenet100-c4fzq57y-ep=399.ckpt"
backbone:
  name: "resnet18"
pretrain_method: "barlow_twins"
data: 
  dataset: custom
  train_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/Officehome/RealWorld/train"
  val_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/Officehome/RealWorld/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
