defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-imagenet100-linear-domainent-sketch-CDS"
pretrained_feature_extractor: /raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/CDS/CDS_pretraining/checkpoint/CDS_domainnet_real_sketch_epoch_6.ckpt
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: custom
  train_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/train"
  val_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [10,20,30,40,50,60,70,80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
