defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-imagenet100-linear-Domainnet-sketch-domainnet_training"
# /raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/pretrained_checkpts/byol/byol-400ep-imagenet100-17qno0qt-ep=399.ckpt
# /raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/trained_models/byol/dcaesu55/byol-imagenet100_diffused_actual_more_domain-dcaesu55-ep=399.ckpt
pretrained_feature_extractor: /raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/trained_models/byol/jlweezg9/byol-imagenet100_diffused_multidomain_real-jlweezg9-ep=399.ckpt
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: custom
  train_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/train"
  val_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [5]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
