defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-imagenet100-linear-domainnet-sketch-new"
pretrained_feature_extractor: /raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/trained_models/mocov3/1dyk3qbu/mocov3-imagenet100-1dyk3qbu-ep=399.ckpt
backbone:
  name: "resnet50"
pretrain_method: "mocov3"
data:
  dataset: custom
  train_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/train"
  val_path: "/raid/biplab/phduser1/Hassan/diffused-solo-learn-main_1/diffused-solo-learn-main/domainnet/domainnet-sketch/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [6]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
